from __future__ import absolute_import
from enum import IntEnum

DataType = IntEnum('DataType', [
    ['UNKNOWN',         0],
    ['BOOLEAN',         1],
    ['BYTE',            2],
    ['INT16',           3],
    ['UINT16',          4],
    ['INT32',           5],
    ['UINT32',          6],
    ['INT64',           7],
    ['UINT64',          8],
    ['STRING',          9],
    ['BYTE_ARRAY',      10],
    ['INT16_ARRAY',     11],
    ['UINT16_ARRAY',    12],
    ['INT32_ARRAY',     13],
    ['UINT32_ARRAY',    14],
    ['INT64_ARRAY',     15],
    ['UINT64_ARRAY',    16],
    ['STRING_ARRAY',    17],
    ['HRTIME',          18],
    ['NVLIST',          19],
    ['NVLIST_ARRAY',    20],
    ['BOOLEAN_VALUE',   21],
    ['INT8',            22],
    ['UINT8',           23],
    ['BOOLEAN_ARRAY',   24],
    ['INT8_ARRAY',      25],
    ['UINT8_ARRAY',     26],
    ['DOUBLE',          27],
])
